Traceback (most recent call last):
  "sintatico.py", line 294, in <module>
    result = parser.parse(data, lexer=lexer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
        ^^^^^^^^^^^^^^^^
  "sintatico.py", line 288, in p_error
    print(f"Erro de sintaxe na linha {p.lineno} - token inesperado: {p.type}")
                                      ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lineno'
PS C:\Users\marce\OneDrive\Documentos\VscodeProjetos\compilador-main>
